<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Chethans-MacBook-Air.local" name="com.pharmeasy.MercuryUI.Gatepass.TC_011_VerifyGatePassUpdation" tests="3" failures="1" timestamp="12 Feb 2019 15:44:07 GMT" time="77.166" errors="0">
  <testcase name="verifyUpdateMSGText" time="21.785" classname="com.pharmeasy.MercuryUI.Gatepass.TC_011_VerifyGatePassUpdation">
    <failure type="java.lang.AssertionError" message="expected [Gatepass Updated Successfully] but found [Gatepass Updated Succcesfully]">
      <![CDATA[java.lang.AssertionError: expected [Gatepass Updated Successfully] but found [Gatepass Updated Succcesfully]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.pharmeasy.MercuryUI.Gatepass.TC_011_VerifyGatePassUpdation.verifyUpdateMSGText(TC_011_VerifyGatePassUpdation.java:32)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1204)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyUpdateMSGText -->
  <testcase name="verifyInvoiceNumUpdate" time="27.807" classname="com.pharmeasy.MercuryUI.Gatepass.TC_011_VerifyGatePassUpdation"/>
  <testcase name="verifyInvoiceAmountUpdate" time="27.574" classname="com.pharmeasy.MercuryUI.Gatepass.TC_011_VerifyGatePassUpdation"/>
</testsuite> <!-- com.pharmeasy.MercuryUI.Gatepass.TC_011_VerifyGatePassUpdation -->
